
package pe.edu.uni.biblioteca.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author FIEECS UNI
 */
public class MainView extends javax.swing.JFrame {

	/**
	 * Creates new form MainView
	 */
	public MainView() {
		initComponents();
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      menuArchivo = new javax.swing.JMenu();
      menuArchivoSalir = new javax.swing.JMenuItem();
      menuProcesos = new javax.swing.JMenu();
      menuProcesosPrestamo = new javax.swing.JMenuItem();
      menuTablas = new javax.swing.JMenu();
      menuUtil = new javax.swing.JMenu();
      menuConsultas = new javax.swing.JMenu();
      menuReportes = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      menuArchivo.setMnemonic('f');
      menuArchivo.setText("Archivo");

      menuArchivoSalir.setMnemonic('x');
      menuArchivoSalir.setText("Salir");
      menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuArchivoSalirActionPerformed(evt);
         }
      });
      menuArchivo.add(menuArchivoSalir);

      menuBar.add(menuArchivo);

      menuProcesos.setText("Procesos");

      menuProcesosPrestamo.setText("Prestamo");
      menuProcesosPrestamo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosPrestamoActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosPrestamo);

      menuBar.add(menuProcesos);

      menuTablas.setText("Tablas");
      menuBar.add(menuTablas);

      menuUtil.setText("Util");
      menuBar.add(menuUtil);

      menuConsultas.setText("Consultas");
      menuBar.add(menuConsultas);

      menuReportes.setText("Reportes");
      menuBar.add(menuReportes);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
		 System.exit(0);
    }//GEN-LAST:event_menuArchivoSalirActionPerformed

   private void menuProcesosPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosPrestamoActionPerformed
      JInternalFrame view = new RegistrarPrestamoView();
		desktopPane.add(view);
		view.setVisible(true);
   }//GEN-LAST:event_menuProcesosPrestamoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenu menuArchivo;
   private javax.swing.JMenuItem menuArchivoSalir;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuConsultas;
   private javax.swing.JMenu menuProcesos;
   private javax.swing.JMenuItem menuProcesosPrestamo;
   private javax.swing.JMenu menuReportes;
   private javax.swing.JMenu menuTablas;
   private javax.swing.JMenu menuUtil;
   // End of variables declaration//GEN-END:variables

}
