/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.edu.uni.biblioteca.view;

import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import pe.edu.uni.biblioteca.controller.ConsultaController;
import pe.edu.uni.biblioteca.dto.Reporte01;

/**
 *
 * @author FIEECS UNI
 */
public class ConsultaView extends javax.swing.JInternalFrame {

	private ConsultaController consultaController;
	
	/**
	 * Creates new form ConsultaView
	 */
	public ConsultaView() {
		initComponents();
		consultaController = new ConsultaController();
		mostrarGrafico();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      panel1 = new javax.swing.JPanel();

      setClosable(true);
      setMaximizable(true);

      javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
      panel1.setLayout(panel1Layout);
      panel1Layout.setHorizontalGroup(
         panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 558, Short.MAX_VALUE)
      );
      panel1Layout.setVerticalGroup(
         panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 265, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel panel1;
   // End of variables declaration//GEN-END:variables

	private void mostrarGrafico() {
		// Obtener datos
		List<Reporte01> lista = consultaController.obtenerReporte01();
	
		// Definiendo la fuente de datos
		DefaultPieDataset data = new DefaultPieDataset();
		for(Reporte01 bean: lista){
			data.setValue(bean.getEtiqueta(), bean.getFrecuencia());
		}
		
		//data.setValue("Artículo 1", 40.55);
		//data.setValue("Artículo 2", 81.23);
		//data.setValue("Artículo 3", 61.54);

		// Creando el gráfico
		JFreeChart chart = ChartFactory.createPieChart(
				  "Ejemplo de Gráfico Tipo Pastel", // Título del gráfico
				  data, // DataSet
				  true, // Leyenda
				  true, // ToolTips
				  true);

// Mostrando el gráfico en un jPanel
		this.panel1.removeAll();
		this.panel1.setLayout(new java.awt.BorderLayout());
		this.panel1.add(new ChartPanel(chart));
		this.panel1.validate();
	}
}
